[package]
name = "loga"
version = "0.1.7"
edition = "2021"
description = "Combined logging and error handling"
license = "ISC"
readme = "readme.md"
repository = "https://github.com/andrewbaxter/loga"

[dependencies]
chrono = "0.4.24"
console = "0.15.7"
textwrap = { version = "0.16.0", features = ["terminal_size"] }
